import 'dart:convert';
import 'dart:typed_data';
import 'package:http/http.dart' as http;
import '../core/config/llm_config.dart';

// Result returned from the Flask backend after a successful /ask call.
class BackendResult {
  final String answer;
  final Uint8List audioBytes; // MP3 from OpenAI TTS generated by Flask

  const BackendResult({required this.answer, required this.audioBytes});
}

// Client for the Flask museum guide backend (app.py).
//
// Endpoints used:
//   POST /ask   — send painting name + question text → get answer + trigger TTS
//   GET  /audio — fetch the generated MP3 file
//
// The Flask server must be running on the same WiFi network as the phone.
// Set the URL in Settings → LLM → Flask URL  (e.g. http://192.168.1.x:5001)
class BackendService {
  // Text-based ask: send painting key + question, receive answer text + MP3.
  // Used while real audio recording (speech-to-text) is not yet integrated.
  Future<BackendResult> ask({
    required String paintingName,
    required String question,
  }) async {
    final base = llmConfig.flaskBaseUrl.trimRight().replaceAll(RegExp(r'/$'), '');

    // Step 1: POST /ask
    final askResponse = await http
        .post(
          Uri.parse('$base/ask'),
          headers: {'Content-Type': 'application/json'},
          body: json.encode({
            'painting_name': paintingName,
            'question': question,
          }),
        )
        .timeout(const Duration(seconds: 20));

    if (askResponse.statusCode != 200) {
      throw Exception('Flask /ask returned ${askResponse.statusCode}');
    }

    final data = json.decode(askResponse.body) as Map<String, dynamic>;
    final answer = data['answer'] as String;

    // Step 2: GET /audio — fetch the MP3 the Flask server just generated
    final audioResponse = await http
        .get(Uri.parse('$base/audio'))
        .timeout(const Duration(seconds: 10));

    if (audioResponse.statusCode != 200) {
      throw Exception('Flask /audio returned ${audioResponse.statusCode}');
    }

    return BackendResult(
      answer: answer,
      audioBytes: audioResponse.bodyBytes,
    );
  }

  // Full process endpoint: sends audio file + painting name + confidence.
  // Used when real microphone recording is integrated (future phase).
  Future<BackendResult> process({
    required String paintingName,
    required double confidence,
    required Uint8List audioBytes, // WAV/M4A recorded on device
  }) async {
    final base = llmConfig.flaskBaseUrl.trimRight().replaceAll(RegExp(r'/$'), '');

    final request = http.MultipartRequest('POST', Uri.parse('$base/process'));
    request.fields['painting_name'] = paintingName;
    request.fields['confidence'] = confidence.toString();
    request.files.add(http.MultipartFile.fromBytes(
      'audio',
      audioBytes,
      filename: 'question.wav',
    ));

    final streamed = await request.send().timeout(const Duration(seconds: 30));
    final response = await http.Response.fromStream(streamed);

    if (response.statusCode != 200) {
      throw Exception('Flask /process returned ${response.statusCode}');
    }

    final data = json.decode(response.body) as Map<String, dynamic>;
    final answer = data['answer'] as String;

    // Fetch the generated MP3
    final audioResponse = await http
        .get(Uri.parse('$base/audio'))
        .timeout(const Duration(seconds: 10));

    return BackendResult(
      answer: answer,
      audioBytes: audioResponse.bodyBytes,
    );
  }
}
